### ISSUE TITLE
[Bug] Clicking on media-dupes 0.4.2 release update notification fails with error

### ISSUE THREAD

**Issue by HabibSay** [yafp/media-dupes#90] opened 2020-02-18 05:18 UTC
```
Error: Cannot find module './js/modules/githubUrls.js'
Require stack:
- C:\Users\hp\AppData\Local\Programs\media-dupes\resources\app\app\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/renderer_init.js:930:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at openReleasesOverview (file:///C:/Users/hp/AppData/Local/Programs/media-dupes/resources/app/app/js/renderer.js:1316:35)
    at NotyButton.Noty.buttons.Noty.button.id [as cb] (file:///C:/Users/hp/AppData/Local/Programs/media-dupes/resources/app/app/js/renderer.js:1269:29)
    at HTMLButtonElement.<anonymous> (C:\Users\hp\AppData\Local\Programs\media-dupes\resources\app\node_modules\noty\lib\noty.js:2496:40)
    at HTMLButtonElement.sentryWrapped (C:\Users\hp\AppData\Local\Programs\media-dupes\resources\app\node_modules\@sentry\browser\dist\helpers.js:74:23)
```

---

media-dupes 0.4.2
Electron 7.1.9
win32 10.0.17763
Locale: fr

**Comment by yafp** [comment] 2020-02-18 06:14
@HabibSay 

Hello and welcome to media-dupes. Hope you enjoy the application so far ;)
Thanks as well for reporting this issue.

The issue is known to me and already fixed in 0.5.0.
I would recommend you update to the current release (0.5.0)

To explain the issue:
I did rename some methods/functions and modules in 0.4.2 and forgot it at once place. As a result the click on the update notification to open the project release page failed.

From your current version (0.4.2) you can easily switch to the release page by clicking in the menu:

> Help -> Releases.

Or just navigate on github itself to: https://github.com/yafp/media-dupes/releases/

I hope 0.5.0 serves you better - it contains a lot of improvements and some fixes ;)

See: https://github.com/yafp/media-dupes/blob/master/docs/CHANGELOG.md


Greetings
yafp

**Closed as completed** 2020-02-18 06:39 UTC
Labels: bug, fixed
